### PR TITLE
French translation

### LINKED ISSUE #24: [Feature] Translations
Thank you for this great application!

Do you have plans for translations?

### PR DESCRIPTION
**Pull request by Glandos**
Fix #24

### CODE REVIEW

**Comment by thetwom** [comment]
Hi, thanks a lot for providing the translations so quickly. Looks quite good already. Android Studio warns me, that the plural translations don't have the `many`-plurals. Could you please check, and add these lines?
E.g.
```
    <plurals name="pitch_history_num_faulty_values_summary">
        <item quantity="one">Aller directement à la nouvelle valeur de la hauteur</item>
        <item quantity="other">Après %d valeurs similaires de hauteur</item>
    </plurals>
```
here add a `many`-quantity, like 
```
    <plurals name="pitch_history_num_faulty_values_summary">
        <item quantity="one">Aller directement à la nouvelle valeur de la hauteur</item>
        <item quantity="many">............</item>
        <item quantity="other">Après %d valeurs similaires de hauteur</item>
    </plurals>
```
and there are a few more plurals.

It appears that this is not needed for other languages like english or german ...

**Comment by Glandos** [comment]
I was confused by the warning you reported, and since it's not my first translation, I have to find resources.
It seems that here, Android Studio is wrong however. [Unicode Language Plural Rules for French](https://www.unicode.org/cldr/cldr-aux/charts/25/supplemental/language_plural_rules.html#fr) only talks about `one` and `other` and it reassured me on my French (we have only those 2 cases, the only difference from English is fractional quantities between 1 and 2)

As a solution, I can just make a copy/paste from `other` to `many`, but that would be puzzling for other contributor. What do you think?

**Comment by thetwom** [comment]
Thanks for the answer. I don't know much about French, so I thought maybe you were just not aware of the option. But since you obviously seem to know, I will just ignore the warning and use it as it is. No need to work around warnings which are wrong :-). I will publish the new version with your translations soon, maybe another rc, such that you quickly test it.

**Comment by thetwom** [comment]
Sorry, I missed one more thing. Can you go to `fastlane/metadata/android`, create a new folder there, `fr`, and add  two files there: `full_description.txt` and `short_description.txt`. These two files should contain the translations of the files with the same names that are in the `en-US` folder. fdroid uses this information to show the app descriptions. Also in google play, I will use these descriptions for the french page.

You can do this directly on the master branch. I merged you translations with minor fixes already there ...

**Comment by Glandos** [comment]
I did it on this PR, it was simpler for me.

**Comment by thetwom** [comment]
This is completely fine. I created a release candidate [v4.0.0-rc9](https://github.com/thetwom/Tuner/releases/tag/v4.0.0-rc9). If you are able to test it, it would be great. If you installed the tuner from fdroid or google-play, you would have to uninstall it before installing the apk, since the signing keys don't match.

**Comment by Glandos** [comment]
I made slight modifications. And one typo.
I didn't see any export options in this version, is it gone?

**Comment by thetwom** [comment]
Great, the export options are still there, but they are now "hidden" in the dots menu. Could you confirm, that you find them, just to be sure everything is working as expected :-).
I pushed your updates to the master. If there are no further corrections from your side and the export-options can be found as expected, I will release the new version soon. 
If you find any issues in future, just let me know, either file a new pull request, or just let me know by leaving and issue ...
Thanks for your work!

**Comment by Glandos** [comment]
I was unable to find the dots menu. I switched to dark theme just in case, and tapped everywhere in the top bar.

Screenshot_20220703-221718
Screenshot_20220703-221737
Screenshot_20220703-221748
Screenshot_20220703-221759

It's Lenovo Tablet with Android 9, because Lenovo didn't provide any update for this device. Maybe it's unsupported?

**Comment by thetwom** [comment]
Thanks for checking. You are right, the dots menu is missing. It was even missing for me! It seems that due to an API update, there was a change of behavior. It should be fixed in [v4.0.0-rc10](https://github.com/thetwom/Tuner/releases/tag/v4.0.0-rc10). Would be great, if you could test again and let me know if it works for you again.

**Comment by thetwom** [comment]
Btw. glad to see, that the layout is working even for tablets, ... but it really looks like there is room for improvement :-).

**Comment by Glandos** [comment]
[**@thetwom**](https://github.com/thetwom) commented on [3 juil. 2022, 23:09 UTC+2](https://github.com/thetwom/Tuner/pull/25#issuecomment-1173172159 "2022-07-03T21:09:03Z - Replied by Github Reply Comments"):
> Thanks for checking. You are right, the dots menu is missing. It was even missing for me! It seems that due to an API update, there was a change of behavior. It should be fixed in [v4.0.0-rc10](https://github.com/thetwom/Tuner/releases/tag/v4.0.0-rc10). Would be great, if you could test again and let me know if it works for you again.

That's working great! And the translation is OK for me.

**Comment by thetwom** [comment]
Great, this is now all merged and released [v4.0.0](https://github.com/thetwom/Tuner/releases/tag/v4.0.0)

**Pull request closed without merging**
