### PR TITLE
Add zh_CN translation strings

### PR DESCRIPTION
**Pull request by BLumia**
I only submitted the translation strings here. I didn't update the `locales_config.xml` file since it seems it's not working on my side and I'm not sure how to get the translation working. If that gets fixed, I'm happy to submit the rest of the strings in further PR.

Feel free to let me know if you need any additional information.

### CODE REVIEW

**Comment by thetwom** [comment]
Thanks a lot for your efforts. So in theory, the app should follow your system language. Regarding the locales config, it is used for per-app language setting. Add zh_CN to the locals_config.xml. And add zh_CN to `resConfigs`-list in `build.gradle`. See also `git show 3a8` .
Let me know if this helps.

**Comment by BLumia** [comment]
> And add zh_CN to `resConfigs`-list in `build.gradle`

Oh, that's the place I missed before, it works! I'll update the patch with the related changes and also add some new translated strings later today. Thanks!

**Comment by BLumia** [comment]
done :)

btw, while translating, I found the 7th note was called "Si" instead of "Ti". I suggest we can have a configuration to let users select to use "Si" or "Ti" since "Ti" is common to see and it's also okay if some users prefer to use "Si". See also: [Wikipedia: Solfege](https://en.wikipedia.org/wiki/Solf%C3%A8ge#:~:text=%22si%22%20was%20changed%20to%20%22ti%22)

**Comment by thetwom** [comment]
Thanks a lot for the further work. Just a few comments.

Could you please also translate app name, description, short description? For this, to into the folder `fastlane/metadata/android/`, at a `zh_CN` folder and add the files `full_description.txt` and ` short_description.txt`. The original files are in the `en-US`-folder. Also consider adding a `title.txt` file for also translating the app name.

Any specific reason for adding the `AppLocalsMetadataService` in the manifest? For me it seems, that this is only needed for older android versions with an in-app language picker, which we don't have. 

Thanks for pointing out the issue about Si and Ti. It seems a difficult choice. About the options, which come to my mind:
- As you say, let the user choose. But this is something I really try to avoid since too many setting are very distracting.
- Set the most common name for each language. In this case, we could choose Ti in English and Si in other languages. However, I really can't say, if there are clear preferences in different languages. So not sure, how to proceed best at this point here.

**Comment by BLumia** [comment]
Patch updated :)

> add the files `full_description.txt`

I didn't add the full description this time because some of the features are a little bit advanced for me and I'm not sure if I can translate them accurately. For the same reason, some strings from the advanced settings are also not translated at this moment. Maybe I'll add the full description translations and other strings' translations in later PRs. Hope that's okay.

> Any specific reason for adding the `AppLocalsMetadataService` in the manifest?

Oh, since the translation wasn't working on my device, that's what I was attempt to add before knowing `resConfigs` is actually the place I need to touch. Patch is now updated to remove these changes.

> As you say, let the user choose. But this is something I really try to avoid since too many setting are very distracting.

Adding an option could be good IMO. I personally don't think it could be distracting. Currently I still can't accurately understand some of the settings under the "Advanced" setting section, but I also don't think those settings caused any sort of distraction.

It's still okay if you don't plan to add this option so feel free to go with the solution that you preferred :)

> Set the most common name for each language.

The reason I prefer setting option over pre-locale/language translation is because users in the same country/region can still prefer to use Ti over Si.

**Comment by thetwom** [comment]
Ok, I see that quite a few strings are not translated yet. Still, we can use this as a start. 

One question for my better understanding. Can you explain why for the strings, we have the code `zh-rCN`, for the locals, we have `zh-CN` and for fastlane we have `zh-Hans`?  I was looking around a bit and it seems to me that e.g. fastlane uses other codes than android. And the `r` in `rCN` stands for "simplified"? But I still did not find further information, why the locals then skip the `r`. I guess you did much better research here, but it would be nice for me to understand better :-). 

It is ok for me, to skip the full description for now. I understand, that some terms are quite technical. 

Regarding settings for "Ti" and "Si": Yes, we already have a lot of settings. But I would rather simplify them to extend them :-). And at the moment it seems, we would either have to add a new notation system (Solfege with Ti). Or add an additional property which gets enabled, when one chooses Solfege. Both versions seems not so elegant. Maybe it is worth to open another issue and request this. So that this question becomes more visible to others. And maybe there is more feedback ...

**Comment by BLumia** [comment]
> One question for my better understanding. Can you explain why for the strings, we have the code zh-rCN, for the locals, we have zh-CN and for fastlane we have zh-Hans? I was looking around a bit and it seems to me that e.g. fastlane uses other codes than android. And the r in rCN stands for "simplified"? But I still did not find further information, why the locals then skip the r. I guess you did much better research here, but it would be nice for me to understand better :-).

Yeah, in Android resources `zh-rCN` is preferred and in fastlane we need to use `zh-Hans` ([fastlane doesn't recognized `zh-CN`](https://github.com/fastlane/fastlane/issues/2318)). The `r` in `zh-rCN` doesn't means it's simplified, for other example, if we want to provide a `en-GB` resource, it will be `en-rGB`.

I also have a working example which can be see here:

- [zh-rCN as Android resource](https://github.com/BLumia/pineapple-lock-screen/blob/master/app/src/main/res/values-zh-rCN/strings.xml)
- [zh-Hans in fastlane](https://github.com/BLumia/pineapple-lock-screen-fastlane/tree/master/free/fastlane/metadata/android/zh-Hans)

> Regarding settings for "Ti" and "Si"... Maybe it is worth to open another issue and request this. So that this question becomes more visible to others. And maybe there is more feedback

Agree, I'll create an issue later :)

**Comment by thetwom** [comment]
Thanks a lot for the explanations. Thanks for opening the Si/Ti issue.

**Pull request merged**
